version: "3.8"
services:
  api:
    build: 
      context: ./server
      target: development
    container_name: /api_c
    ports:
      - "4000:4000"
    volumes:
      - './server:/api'
      - '/api/node_modules'
    command: npm run dev

  client:
    build: ./client
    container_name: /client_c
    ports:
      - "5173:5173"
    volumes:
      - './client:/client'
      - '/client/node_modules'
    stdin_open: true
    tty: true
